### PR TITLE
added a boolean flag for generate QR

### PR DESCRIPTION
**Pull request by marti1125**
* WIP

example
```
./bin/pspk --name cat publish --qr
```

imagen

### CODE REVIEW

**Comment by marti1125** [comment]
I just added the flag --path

imagen

**Comment by marti1125** [comment]
I think I finished the implementation

**Comment by marti1125** [comment]
could you merge this pr ?

**Comment by sah4ez** [comment]
@marti1125  Thanks! Sorry for the delay!

**Comment by marti1125** [comment]
@sah4ez  any issue you can suggest me ?

**Comment by sah4ez** [comment]
@marti1125 you can see #50

**Pull request merged**
